import type {
  Room,
  Reservation,
  Guest,
  Channel,
  SeasonalPricing,
  Coupon,
  DailyStats,
  ChannelStats,
  Review,
  PropertyInfo,
  RoomAvailability,
  AdminCoupon,
} from '@/types'

// Property Info
export const propertyInfo: PropertyInfo = {
  name: 'Heated Pool & Coffee Bar • 5 minutes to Madeira Beach',
  description:
    'Welcome to Areia Bela, just 5 minutes from Madeira Beach! Enjoy a private heated pool, Smart Toilet, BBQ, full coffee bar, selfie station, and game corner with Bubble Surprise for kids. Pet-friendly with treats, fully stocked kitchen, unlimited Wi-Fi, and in-room QR codes for dining & local adventures. Comfort, fun, and unforgettable memories in one family- and group-friendly beach getaway.',
  address: 'San Petersburgo, Florida, Estados Unidos',
  city: 'St. Petersburg',
  country: 'United States',
  phone: '+1 (555) 987-6543',
  email: 'host@areiabela.com',
  website: 'www.areiabela.com',
  checkInTime: '16:00',
  checkOutTime: '10:00',
  amenities: [
    'Cocina',
    'Aparcamiento gratuito en las instalaciones',
    'Wifi',
    'Piscina',
    'Zona para trabajar',
    'Perchas',
    'TV',
    'Secadora',
    'Champú',
    'Lavadora',
    'Secador de pelo',
    'Servicios básicos',
    'Aire acondicionado',
    'Calefacción',
    'Aparcamiento gratuito en la calle',
    'Detector de humo',
    'Detector de monóxido de carbono',
    'Botiquín',
    'Extintor de incendios',
    'Cerradura con teclado',
    'Entrada privada',
    'Bañera',
    'Agua caliente',
    'Gel de ducha',
    'Ropa de cama',
    'Microondas',
    'Cafetera',
    'Nevera',
    'Lavavajillas',
    'Platos y cubiertos',
    'Utensilios básicos de cocina',
    'Horno',
    'Fogones',
    'Barbacoa',
    'Patio trasero',
    'Básicos de playa',
    'Bicicletas',
    'Juegos de mesa',
    'Cafetera Keurig',
    'Productos de limpieza',
  ],
  policies: [
    'Check-in: 4:00 PM - Check-out: 10:00 AM',
    'No se permiten fiestas ni eventos',
    'Admite mascotas',
    'Prohibido fumar',
    'Exterior security cameras present',
  ],
  images: [
    'https://a0.muscache.com/im/pictures/hosting/Hosting-1489399156507737323/original/40a17db2-7992-4580-a222-d8fe07087e28.jpeg?aki_policy=large',
    'https://a0.muscache.com/im/pictures/hosting/Hosting-1489399156507737323/original/c3e81b9b-8fd0-4334-b82d-ad919bea2bbe.jpeg?aki_policy=large',
    'https://a0.muscache.com/im/pictures/hosting/Hosting-1489399156507737323/original/58ef08d8-d3f4-4722-a5cf-d57284cc2beb.jpeg?aki_policy=large',
    'https://a0.muscache.com/im/pictures/hosting/Hosting-1489399156507737323/original/942777bf-4cd4-48cd-9730-5f71dd72b2c8.jpeg?aki_policy=large',
    'https://a0.muscache.com/im/pictures/hosting/Hosting-1489399156507737323/original/018ab8d8-2e04-4320-a60c-a7dd61c8a9e2.jpeg?aki_policy=large',
    'https://a0.muscache.com/im/pictures/hosting/Hosting-1489399156507737323/original/fc8b39e6-bddc-4ebf-b041-23bfa8fce12a.jpeg?aki_policy=large',
    'https://a0.muscache.com/im/pictures/hosting/Hosting-1489399156507737323/original/5fc2ddfb-7bc8-4e78-8ac4-cd287e41955e.jpeg?aki_policy=large',
    'https://a0.muscache.com/im/pictures/hosting/Hosting-1489399156507737323/original/60040006-8fd7-4dfc-ae4c-ef3d29a2cce8.jpeg?aki_policy=large',
    'https://a0.muscache.com/im/pictures/hosting/Hosting-1489399156507737323/original/98aecab8-e3cb-4551-9aa1-cefd97509e25.jpeg?aki_policy=large',
    'https://a0.muscache.com/im/pictures/hosting/Hosting-1489399156507737323/original/36ac1e34-a959-494b-a691-a278367aa1a9.jpeg?aki_policy=large',
  ],
}

// Rooms (Keeping structure but adapting to full-property rental or multiple distinct rooms inside the property for UI purposes)
export const rooms: Room[] = [
  {
    id: '1489399156507737323',
    type: 'luxury-suite',
    name: 'Heated Pool & Coffee Bar• 5-min to Madeira Beach',
    description:
      'Welcome to Areia Bela, just 5 minutes from Madeira Beach! Enjoy a private heated pool, Smart Toilet, BBQ, full coffee bar, selfie station, and game corner with Bubble Surprise for kids. Pet-friendly with treats, fully stocked kitchen, unlimited Wi-Fi, and in-room QR codes for dining & local adventures.',
    capacity: 8,
    beds: '3 Bedrooms',
    size: 150,
    amenities: [
      'Wifi',
      'Piscina',
      'Aire acondicionado',
      'Cocina',
      'Lavadora',
      'Secadora',
      'TV',
      'Bicicletas',
      'Barbacoa',
      'Pet Friendly',
    ],
    images: ['coffee_bar.png', 'coffee_bar.png', 'coffee_bar.png', 'coffee_bar.png'],
    basePrice: 250,
    inventory: 1,
  },
]

// Guests
export const guests: Guest[] = [
  {
    id: 'guest-1',
    name: 'Emily Johnson',
    email: 'emily.johnson@email.com',
    phone: '+1 (555) 234-5678',
    country: 'United States',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
    totalStays: 5,
    totalSpending: 4500,
    notes: 'VIP guest. Prefers ocean view rooms.',
    createdAt: '2024-01-15',
    lastStay: '2025-12-20',
  },
  {
    id: 'guest-2',
    name: 'Michael Chen',
    email: 'michael.chen@email.com',
    phone: '+1 (555) 345-6789',
    country: 'Canada',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
    totalStays: 3,
    totalSpending: 2800,
    notes: 'Business traveler. Late check-out requested.',
    createdAt: '2024-03-20',
    lastStay: '2025-11-15',
  },
  {
    id: 'guest-3',
    name: 'Sofia Rodriguez',
    email: 'sofia.rodriguez@email.com',
    phone: '+34 612 345 678',
    country: 'Spain',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
    totalStays: 2,
    totalSpending: 3200,
    createdAt: '2024-06-10',
    lastStay: '2025-10-05',
  },
  {
    id: 'guest-4',
    name: 'James Wilson',
    email: 'james.wilson@email.com',
    phone: '+44 7911 123456',
    country: 'United Kingdom',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100',
    totalStays: 8,
    totalSpending: 12500,
    notes: 'Platinum member. Anniversary every June.',
    createdAt: '2023-08-22',
    lastStay: '2026-01-10',
  },
  {
    id: 'guest-5',
    name: 'Yuki Tanaka',
    email: 'yuki.tanaka@email.com',
    phone: '+81 90-1234-5678',
    country: 'Japan',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
    totalStays: 1,
    totalSpending: 850,
    createdAt: '2025-02-14',
    lastStay: '2025-02-18',
  },
  {
    id: 'guest-6',
    name: 'Alexander Müller',
    email: 'alexander.muller@email.com',
    phone: '+49 170 1234567',
    country: 'Germany',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100',
    totalStays: 4,
    totalSpending: 5600,
    notes: 'Prefers quiet rooms. Dietary restrictions: vegetarian.',
    createdAt: '2024-02-28',
    lastStay: '2025-12-01',
  },
]

export const reservations: Reservation[] = [
  {
    id: 'res-1',
    guestId: 'guest-1',
    guestName: 'Emily Johnson',
    guestEmail: 'emily.johnson@email.com',
    guestPhone: '+1 (555) 234-5678',
    roomId: 'room-4',
    roomType: 'luxury-suite',
    roomName: 'Luxury Suite',
    checkIn: '2026-03-15',
    checkOut: '2026-03-20',
    guests: 2,
    adults: 2,
    children: 0,
    status: 'confirmed',
    totalPrice: 3575,
    nightPrice: 650,
    cleaningFee: 75,
    serviceFee: 125,
    taxes: 325,
    specialRequests: 'Late check-in around 10 PM. Champagne on arrival.',
    paymentMethod: 'stripe',
    channel: 'direct',
    createdAt: '2026-02-20',
    updatedAt: '2026-02-20',
  },
  {
    id: 'res-2',
    guestId: 'guest-2',
    guestName: 'Michael Chen',
    guestEmail: 'michael.chen@email.com',
    guestPhone: '+1 (555) 345-6789',
    roomId: 'room-2',
    roomType: 'deluxe',
    roomName: 'Deluxe Room',
    checkIn: '2026-03-10',
    checkOut: '2026-03-12',
    guests: 1,
    adults: 1,
    children: 0,
    status: 'checked-in',
    totalPrice: 575,
    nightPrice: 250,
    cleaningFee: 35,
    serviceFee: 40,
    taxes: 50,
    paymentMethod: 'stripe',
    channel: 'booking',
    createdAt: '2026-02-15',
    updatedAt: '2026-03-10',
  },
  {
    id: 'res-3',
    guestId: 'guest-3',
    guestName: 'Sofia Rodriguez',
    guestEmail: 'sofia.rodriguez@email.com',
    guestPhone: '+34 612 345 678',
    roomId: 'room-3',
    roomType: 'family-suite',
    roomName: 'Family Suite',
    checkIn: '2026-03-18',
    checkOut: '2026-03-25',
    guests: 4,
    adults: 2,
    children: 2,
    status: 'pending',
    totalPrice: 3220,
    nightPrice: 400,
    cleaningFee: 60,
    serviceFee: 100,
    taxes: 260,
    specialRequests: 'Baby crib needed. Allergies to nuts.',
    channel: 'airbnb',
    createdAt: '2026-03-01',
    updatedAt: '2026-03-01',
  },
  {
    id: 'res-4',
    guestId: 'guest-4',
    guestName: 'James Wilson',
    guestEmail: 'james.wilson@email.com',
    guestPhone: '+44 7911 123456',
    roomId: 'room-5',
    roomType: 'penthouse',
    roomName: 'Penthouse Suite',
    checkIn: '2026-03-05',
    checkOut: '2026-03-08',
    guests: 2,
    adults: 2,
    children: 0,
    status: 'checked-out',
    totalPrice: 3960,
    nightPrice: 1200,
    cleaningFee: 100,
    serviceFee: 180,
    taxes: 360,
    paymentMethod: 'apple-pay',
    channel: 'direct',
    createdAt: '2026-02-10',
    updatedAt: '2026-03-08',
  },
  {
    id: 'res-5',
    guestId: 'guest-5',
    guestName: 'Yuki Tanaka',
    guestEmail: 'yuki.tanaka@email.com',
    guestPhone: '+81 90-1234-5678',
    roomId: 'room-1',
    roomType: 'standard',
    roomName: 'Standard Room',
    checkIn: '2026-03-12',
    checkOut: '2026-03-14',
    guests: 1,
    adults: 1,
    children: 0,
    status: 'confirmed',
    totalPrice: 365,
    nightPrice: 150,
    cleaningFee: 25,
    serviceFee: 30,
    taxes: 35,
    channel: 'expedia',
    createdAt: '2026-03-05',
    updatedAt: '2026-03-05',
  },
  {
    id: 'res-6',
    guestId: 'guest-6',
    guestName: 'Alexander Müller',
    guestEmail: 'alexander.muller@email.com',
    guestPhone: '+49 170 1234567',
    roomId: 'room-2',
    roomType: 'deluxe',
    roomName: 'Deluxe Room',
    checkIn: '2026-03-20',
    checkOut: '2026-03-27',
    guests: 2,
    adults: 2,
    children: 0,
    status: 'confirmed',
    totalPrice: 2025,
    nightPrice: 250,
    cleaningFee: 35,
    serviceFee: 90,
    taxes: 175,
    specialRequests: 'Vegetarian breakfast. Quiet room away from elevator.',
    paymentMethod: 'stripe',
    channel: 'booking',
    createdAt: '2026-02-25',
    updatedAt: '2026-02-25',
  },
  {
    id: 'res-7',
    guestId: 'guest-1',
    guestName: 'Emily Johnson',
    guestEmail: 'emily.johnson@email.com',
    guestPhone: '+1 (555) 234-5678',
    roomId: 'room-1',
    roomType: 'standard',
    roomName: 'Standard Room',
    checkIn: '2026-02-01',
    checkOut: '2026-02-03',
    guests: 1,
    adults: 1,
    children: 0,
    status: 'cancelled',
    totalPrice: 365,
    nightPrice: 150,
    cleaningFee: 25,
    serviceFee: 30,
    taxes: 35,
    channel: 'direct',
    createdAt: '2026-01-20',
    updatedAt: '2026-01-25',
  },
]

export const channels: Channel[] = [
  {
    id: 'channel-1',
    name: 'Airbnb',
    logo: '/channels/airbnb.svg',
    status: 'connected',
    lastSync: '2026-03-10T14:30:00',
    reservations: 45,
    revenue: 42500,
  },
  {
    id: 'channel-2',
    name: 'Booking.com',
    logo: '/channels/booking.svg',
    status: 'syncing',
    lastSync: '2026-03-10T14:25:00',
    reservations: 78,
    revenue: 65200,
  },
  {
    id: 'channel-3',
    name: 'Expedia',
    logo: '/channels/expedia.svg',
    status: 'connected',
    lastSync: '2026-03-10T14:20:00',
    reservations: 32,
    revenue: 28400,
  },
]

export const seasonalPricing: SeasonalPricing[] = [
  {
    id: 'season-1',
    name: 'Winter Low Season',
    type: 'low',
    startDate: '2026-01-05',
    endDate: '2026-02-28',
    multiplier: 0.85,
  },
  {
    id: 'season-2',
    name: 'Spring Break',
    type: 'high',
    startDate: '2026-03-15',
    endDate: '2026-04-15',
    multiplier: 1.25,
  },
  {
    id: 'season-3',
    name: 'Summer Peak',
    type: 'high',
    startDate: '2026-06-15',
    endDate: '2026-08-31',
    multiplier: 1.4,
  },
  {
    id: 'season-4',
    name: 'Thanksgiving',
    type: 'holiday',
    startDate: '2026-11-20',
    endDate: '2026-11-30',
    multiplier: 1.5,
  },
  {
    id: 'season-5',
    name: 'Christmas & New Year',
    type: 'holiday',
    startDate: '2026-12-20',
    endDate: '2027-01-05',
    multiplier: 1.75,
  },
]

// Coupons
export const coupons: Coupon[] = [
  {
    id: 'coupon-1',
    code: 'WELCOME10',
    discountType: 'percentage',
    discountValue: 10,
    expirationDate: '2026-12-31',
    usageLimit: 100,
    usedCount: 42,
    active: true,
    createdAt: '2026-01-01',
  },
  {
    id: 'coupon-2',
    code: 'SUMMER15',
    discountType: 'percentage',
    discountValue: 15,
    expirationDate: '2026-08-31',
    usageLimit: 50,
    usedCount: 18,
    active: true,
    minStay: 3,
    createdAt: '2026-05-01',
  },
  {
    id: 'coupon-3',
    code: 'VIP20',
    discountType: 'percentage',
    discountValue: 20,
    expirationDate: '2026-06-30',
    usageLimit: 25,
    usedCount: 8,
    active: true,
    minStay: 5,
    createdAt: '2026-01-15',
  },
  {
    id: 'coupon-4',
    code: 'FLAT50',
    discountType: 'fixed',
    discountValue: 50,
    expirationDate: '2026-04-30',
    usageLimit: 200,
    usedCount: 156,
    active: true,
    createdAt: '2026-02-01',
  },
  {
    id: 'coupon-5',
    code: 'SPRING25',
    discountType: 'percentage',
    discountValue: 25,
    expirationDate: '2026-03-01',
    usageLimit: 30,
    usedCount: 30,
    active: false,
    createdAt: '2026-02-15',
  },
]

export const dailyStats: DailyStats[] = Array.from({ length: 30 }, (_, i) => {
  const date = new Date()
  date.setDate(date.getDate() - (29 - i))
  const dateStr = date.toISOString().split('T')[0]
  const isWeekend = date.getDay() === 0 || date.getDay() === 6

  return {
    date: dateStr,
    reservations: Math.floor(Math.random() * 8) + (isWeekend ? 5 : 2),
    revenue: Math.floor(Math.random() * 8000) + (isWeekend ? 6000 : 3000),
    occupancyRate: Math.floor(Math.random() * 30) + (isWeekend ? 65 : 45),
    avgNightlyRate: Math.floor(Math.random() * 150) + 250,
    checkIns: Math.floor(Math.random() * 5) + 1,
    checkOuts: Math.floor(Math.random() * 5) + 1,
  }
})

export const channelStats: ChannelStats[] = [
  {
    channelId: 'direct',
    channelName: 'Direct Booking',
    reservations: 89,
    revenue: 58500,
    percentage: 35,
  },
  {
    channelId: 'channel-2',
    channelName: 'Booking.com',
    reservations: 78,
    revenue: 65200,
    percentage: 28,
  },
  {
    channelId: 'channel-1',
    channelName: 'Airbnb',
    reservations: 45,
    revenue: 42500,
    percentage: 22,
  },
  {
    channelId: 'channel-3',
    channelName: 'Expedia',
    reservations: 32,
    revenue: 28400,
    percentage: 15,
  },
]

// Reviews
export const reviews: Review[] = [
  {
    id: '1631349364838882271',
    guestName: 'Jane',
    guestAvatar:
      'https://a0.muscache.com/im/pictures/user/User/original/86b21a30-7428-4a8e-a348-f5905502c9d1.jpeg',
    reservationId: 'res-1',
    roomType: 'casa',
    rating: 5,
    comment:
      'Nuestra estancia de un mes fue más de lo que esperábamos. Esta casa es adorable. Me sentí como en casa desde el primer día. Hermosamente decorado y actualizado. Barrio tranquilo y a 5 minutos en coche de Madeira Beach. Los anfitriones respondieron de inmediato a cualquier duda menor que tuviéramos.',
    cleanliness: 5,
    location: 5,
    service: 5,
    value: 5,
    createdAt: '2026-02-28',
  },
  {
    id: '1579932103126731326',
    guestName: 'Brendan',
    guestAvatar:
      'https://a0.muscache.com/im/pictures/user/User/original/50cc5d04-b56a-4ddd-a7ae-9795c0a89de4.jpeg',
    reservationId: 'res-2',
    roomType: 'casa',
    rating: 5,
    comment:
      'Mi familia tuvo una estancia increíble. A los niños les encantó la piscina climatizada y a nosotros nos encantó el jacuzzi privado. Utilizamos las bicicletas que nos proporcionaron para desplazarnos, porque todo estaba muy cerca. La casa estaba extremadamente limpia y acogedora.',
    cleanliness: 5,
    location: 5,
    service: 5,
    value: 5,
    createdAt: '2025-12-19',
  },
  {
    id: '1565347923697077173',
    guestName: 'Kim',
    guestAvatar:
      'https://a0.muscache.com/im/pictures/user/cb793f97-04f5-49cc-ab97-265140b09685.jpg',
    reservationId: 'res-3',
    roomType: 'casa',
    rating: 4,
    comment:
      'Supercomunicativo, los anfitriones eran encantadores. Justo lo que necesitábamos para nuestras vacaciones.',
    cleanliness: 4,
    location: 4,
    service: 4,
    value: 4,
    createdAt: '2025-11-29',
  },
  {
    id: '1557462157452668388',
    guestName: 'Shelley',
    guestAvatar:
      'https://a0.muscache.com/im/Portrait/Avatars/messaging/b3e03835-ade9-4eb7-a0bb-2466ab9a534d.jpg?im_t=S&im_w=240&im_f=airbnb-cereal-medium.ttf&im_c=ffffff',
    reservationId: 'res-4',
    roomType: 'casa',
    rating: 5,
    comment:
      'La casa de Angelica está bellamente decorada con un ambiente playero. Pudimos ir en bicicleta a bares, restaurantes y tiendas. Angelica fue muy receptiva y respondió rápidamente a todas mis preguntas.',
    cleanliness: 5,
    location: 5,
    service: 5,
    value: 5,
    createdAt: '2025-11-18',
  },
  {
    id: '1539256083714683989',
    guestName: 'Angela',
    guestAvatar:
      'https://a0.muscache.com/im/pictures/user/User/original/b322b4da-8e76-4a48-86cb-4ea76d262583.jpeg',
    reservationId: 'res-5',
    roomType: 'casa',
    rating: 5,
    comment: 'El anfitrión respondió rápidamente. La casa era bonita.',
    cleanliness: 5,
    location: 5,
    service: 5,
    value: 5,
    createdAt: '2025-10-24',
  },
  {
    id: '1536416297532015016',
    guestName: 'Kennette',
    guestAvatar:
      'https://a0.muscache.com/im/pictures/user/17717ccc-a7b0-434f-a41d-780667bf17e0.jpg',
    reservationId: 'res-1',
    roomType: 'casa',
    rating: 5,
    comment:
      '¡Disfrutamos mucho de nuestra estancia de fin de semana! Aunque no pasamos mucho tiempo en la casa, estaba limpia, cómoda y tenía todo lo que necesitábamos. La zona de la piscina era absolutamente hermosa y tranquila.',
    cleanliness: 5,
    location: 5,
    service: 5,
    value: 5,
    createdAt: '2025-10-20',
  },
  {
    id: '1526934009560979894',
    guestName: 'Michelle',
    guestAvatar:
      'https://a0.muscache.com/im/pictures/user/User/original/d711f364-6aea-4087-8fda-adfbd333754a.jpeg',
    reservationId: 'res-2',
    roomType: 'casa',
    rating: 5,
    comment:
      '¡Nos encantó este alojamiento! Estaba a 5 minutos de la playa y Walmart estaba a la vuelta de la esquina. Los niños disfrutaron de la piscina... ¡Sin duda, volveríamos a repetir! La anfitriona también fue genial.',
    cleanliness: 5,
    location: 5,
    service: 5,
    value: 5,
    createdAt: '2025-10-07',
  },
  {
    id: '1515354565141340879',
    guestName: 'Christopher',
    guestAvatar:
      'https://a0.muscache.com/im/pictures/user/d28674e6-a1d3-4000-a89e-eb1a71739d57.jpg',
    reservationId: 'res-3',
    roomType: 'casa',
    rating: 5,
    comment:
      '¡Gran estancia! ¡A mi familia le encantó este Airbnb! Los anfitriones fueron educados y la hospitalidad fue absolutamente impresionante, ¡volveremos!',
    cleanliness: 5,
    location: 5,
    service: 5,
    value: 5,
    createdAt: '2025-09-21',
  },
  {
    id: '1506691483231641240',
    guestName: 'Eduardo',
    guestAvatar:
      'https://a0.muscache.com/im/pictures/user/User/original/c20a09e1-99b3-43ba-ae73-810a740cd782.jpeg',
    reservationId: 'res-4',
    roomType: 'casa',
    rating: 5,
    comment:
      'Ya me había alojado en San Petersburgo antes, pero el Airbnb de Angelica ha sido la experiencia más especial hasta la fecha. Todas las habitaciones tenían códigos QR con actividades divertidas. La casa era exactamente igual que en las fotos.',
    cleanliness: 5,
    location: 5,
    service: 5,
    value: 5,
    createdAt: '2025-09-09',
  },
  {
    id: '1505216952857874565',
    guestName: 'Lucy',
    guestAvatar:
      'https://a0.muscache.com/im/pictures/user/232918a1-a94a-4fe8-80e6-ab307e7bda0f.jpg',
    reservationId: 'res-5',
    roomType: 'casa',
    rating: 5,
    comment:
      '¡Tengo una estancia increíble! También estaba celebrando mi aniversario y tuvieron un pequeño detalle. ¡Con una botella de champán y una tarjeta! Eso fue increíble.❤️',
    cleanliness: 5,
    location: 5,
    service: 5,
    value: 5,
    createdAt: '2025-09-07',
  },
]

// Generate availability for next 60 days
export function generateAvailability(): RoomAvailability[] {
  const availability: RoomAvailability[] = []
  const today = new Date()

  rooms.forEach((room) => {
    for (let i = 0; i < 60; i++) {
      const date = new Date(today)
      date.setDate(date.getDate() + i)
      const dateStr = date.toISOString().split('T')[0]

      // Random availability
      const availableRooms = Math.floor(Math.random() * (room.inventory + 1))
      let status: RoomAvailability['status'] = 'available'

      if (availableRooms === 0) {
        status = 'sold-out'
      } else if (availableRooms === 1) {
        status = 'limited'
      } else if (Math.random() < 0.05) {
        status = 'blocked'
      }

      // Calculate seasonal price
      let priceMultiplier = 1
      const isWeekend = date.getDay() === 0 || date.getDay() === 6
      if (isWeekend) priceMultiplier *= 1.15

      seasonalPricing.forEach((season) => {
        const start = new Date(season.startDate)
        const end = new Date(season.endDate)
        if (date >= start && date <= end) {
          priceMultiplier = season.multiplier
        }
      })

      availability.push({
        roomId: room.id,
        date: dateStr,
        available: status === 'blocked' ? 0 : availableRooms,
        status,
        price: Math.round(room.basePrice * priceMultiplier),
      })
    }
  })

  return availability
}

export const mockCoupons: AdminCoupon[] = [
  {
    id: 'c-1',
    code: 'WELCOME10',
    description: '10% off for first-time guests',
    type: 'percentage',
    value: 10,
    minBooking: 200,
    maxUses: 100,
    usedCount: 42,
    validFrom: '2026-01-01',
    validUntil: '2026-12-31',
    status: 'active',
  },
  {
    id: 'c-2',
    code: 'SUMMER25',
    description: '25% off summer stays',
    type: 'percentage',
    value: 25,
    minBooking: 500,
    maxUses: 50,
    usedCount: 18,
    validFrom: '2026-06-01',
    validUntil: '2026-08-31',
    status: 'active',
  },
  {
    id: 'c-3',
    code: 'FLAT100',
    description: '$100 off any booking',
    type: 'fixed',
    value: 100,
    minBooking: 400,
    maxUses: 200,
    usedCount: 156,
    validFrom: '2026-02-01',
    validUntil: '2026-04-30',
    status: 'active',
  },
  {
    id: 'c-4',
    code: 'VIP20',
    description: 'VIP member exclusive 20% off',
    type: 'percentage',
    value: 20,
    usedCount: 8,
    validFrom: '2026-01-01',
    validUntil: '2026-12-31',
    status: 'active',
  },
  {
    id: 'c-5',
    code: 'SPRING15',
    description: 'Spring sale discount',
    type: 'percentage',
    value: 15,
    maxUses: 30,
    usedCount: 30,
    validFrom: '2026-02-15',
    validUntil: '2026-03-01',
    status: 'expired',
  },
]
